"""seeding database

Revision ID: 82f9da50cb81
Revises: e513b9fc22f6
Create Date: 2024-03-27 13:40:05.200174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f9da50cb81'
down_revision = 'e513b9fc22f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
